repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.3.1 
    hooks:
      - id: autopep8
        args: [--aggressive, --aggressive]

  - repo: https://github.com/pre-commit/mirrors-bandit
    rev: v1.7.9
    hooks:
      - id: bandit
        args: ['-r', '.']

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.2.7
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]