name: systems.org system0

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
            
      - name: Install dependencies
        run: |
             pip install pytest pytest-cov
      
      - name: Install pytest in hw2
        working-directory: hw2
        run: pip install pytest pytest-cov
      
      - name: Test with pytest
        run: pytest --cov=myfile --cov-report=xml
      
      - name: Testing in hw2
        working-directory: hw2
        run: pytest --cov=myfile --cov-report=xml
        
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: 118dc41a-50b7-40cf-b989-623dcdbe28d5
          files: ./coverage.xml
          fail_ci_if_error: true